### ISSUE TITLE
How do I handle CT images with three phases?

### ISSUE THREAD

**Issue by gxw-ll** [vsangelidakis/CLUMP#5]
Hello Prof. Angelidakis, thank you very much for the clump script. It has been extremely helpful for me as a beginner in facilitating the conversion of CT images into discrete metamodels. I have a question: my CT images contain three phases， respectively: such as matrix = 0, hydrate = 2 ,and pore = 1 . How do I handle this with a clump script?

**Comment by gxw-ll** [comment]
Additionally, when running Example_Euclidean_3D.m and selecting the file Binary_3D_Cube.mat, my program gives an error. Below is the error message：
`inputGeom='ParticleGeometries/Binary_3D_Cube.mat';
>> [mesh, clump]=GenerateClump_Euclidean_3D( inputGeom, N, rMin, div, overlap, output, visualise ); % true to plot mesh and clump
creating surface and tetrahedral mesh from a multi-domain volume ...
'which' 不是内部或外部命令，也不是可运行的程序 
或批处理文件。 
错误使用 fallbackexeext (line 37)
The following executable:
	E:\script\matlab_script\CLUMP_MATLAB\lib\iso2mesh\bin\cgalmesh.exe
is missing. Please download it from https://github.com/fangq/iso2mesh/tree/master/bin/ and save it to the above path, then rerun the script.


出错 cgalv2m (line 50)
exesuff=fallbackexeext(exesuff,'cgalmesh');

出错 vol2mesh (line 54)
		[node elem,face]=cgalv2m(vol,opt,maxvol);

出错 v2m (line 18)
[node,elem,face]=vol2mesh(img,1:size(img,1),1:size(img,2),1:size(img,3),opt,maxvol,1,method,isovalues);

出错 v2s (line 21)
   [no,tet,el]=v2m(uint8(img),isovalues,opt,1000,method);

出错 GenerateClump_Euclidean_3D (line 165)
			[P,F]=v2s(vox.img,isovalues,opt,'cgalmesh');
`
![1](https://github.com/user-attachments/assets/9bfe53f0-407a-44f2-9146-5d28e7251ad3)

**Comment by vsangelidakis** [comment]
Hi Xiwei,

Happy to hear CLUMP is helpful to you. To answer your first question, first I need to know which phase you want to approximate with multispheres - is it the hydrate? If yes, is the hydrate a single particle that will be approximated by a single multisphere or various different particles that need separate multispheres?

Regarding your second question, are you running CLUMP in Windows, Linux or Mac? Depending on your OS, you might need to download a different version of iso2mesh, also suggested in the error you get, as we are currently porting this external dependency as binaries that were built for Windows by default.

Best, Vasileios

**Comment by gxw-ll** [comment]
Thank you, Professor, for your prompt response! Yes, I do need to separate multispheres of various particles. I'm working on Windows, and following your suggestion, I replaced the old iso2mesh with the latest version `https://github.com/fangq/iso2mesh` .However, when I focus solely on the matrix phase, the program reports the following error:

![1](https://github.com/user-attachments/assets/d6681c53-2cfa-4789-a180-e0e16e5f0767)
The image of my grid is：
![2](https://github.com/user-attachments/assets/3cc6f5c2-09f2-4589-bfa8-397bdcd40471)

**Comment by vsangelidakis** [comment]
This seems to be a CGAL issue related which happens due to the complex shape of your hydrates. You import them as a single image, and cgal cannot transform the 3D image into a mesh. First and foremost, you need to pre-process your image in an image processing software package, such as FIJI, where you need to segment all the different hydrate particles, label them, and then feed the labelled image in MATLAB, and generate clumps for each hydrate particle separately. When you add your current image in CLUMP, it tries to generate a single clump for it, which is not what you aim to do.

**Comment by gxw-ll** [comment]
Thank you very much, Professor, for your help.

**Comment by vsangelidakis** [comment]
There
