### ISSUE TITLE
Problems with particle position

### ISSUE THREAD

**Issue by gxw-ll** [vsangelidakis/CLUMP#6]
![hydrate6_hydrate](https://github.com/user-attachments/assets/ef606903-e326-4df8-abaa-6d5da639b16b)
![hydrate8_hydrate](https://github.com/user-attachments/assets/6e818ab5-9065-45db-b439-8fbc53e7e7cf)
Hi Professor, I would like to know why the axes don't start from 0. I extracted the spherical coordinates and some of the horizontal x coordinates start from 2*10-3 and some from -1.5*10-3, why does this happen and how can I correct this problem?

**Comment by vsangelidakis** [comment]
Hi @gxw-ll , is the input imaging data given via an .stl file or via a voxelated image? CLUMP will generate multi-spheres at the same coordinate system as your input imaging data. 

There are two easy solutions for this:

1. You can either modify your input imaging data to start from (0,0,0) before clump generation, or 
2. You can move the whole multi-sphere start from (0,0,0) after clump generation, e.g. using something like this:

```
clc; clear; close all

%% Generate test clump
clump=rand(10,4); %x,y,z,r

%% Calculate minimum coordinates (x,y,z)min
minCoordinates=min(clump(:,1:3));

%% Make clump bounding box coordinates start from (0,0,0)
clump(:,1)=clump(:,1)-minCoordinates(1)+clump(:,4);
clump(:,2)=clump(:,2)-minCoordinates(2)+clump(:,4);
clump(:,3)=clump(:,3)-minCoordinates(3)+clump(:,4);

%% Plot clump
visualise=true;
if visualise	
	axis equal
	camlight
	box on; grid on
	alpha 0.5
	[X,Y,Z]=sphere(50);
	for i=1:length(clump(:,4))
		hold on
		x=clump(i,1);
		y=clump(i,2);
		z=clump(i,3);
		r=clump(i,4);
		surf(r*X+x, r*Y+y, r*Z+z, 'FaceColor',rand(1,3), 'EdgeColor','none','FaceAlpha',1)
    end
    xlabel('x')
    ylabel('y')
    zlabel('z')
end
```

Hope this helps,
Vasileios

**Comment by gxw-ll** [comment]
> Hi @gxw-ll , 输入成像数据是通过 .stl 文件还是通过体素化图像提供的？CLUMP 将在与输入成像数据相同的坐标系下生成多个球体。
> 
> 有两种简单的解决方案：
> 
> 1. 您可以在生成束之前将输入成像数据修改为从 （0,0,0） 开始，或者
> 2. 在成束生成后，你可以从 （0,0,0） 开始移动整个多球体，例如，使用如下代码：
> 
> ```
> clc; clear; close all
> 
> %% Generate test clump
> clump=rand(10,4); %x,y,z,r
> 
> %% Calculate minimum coordinates (x,y,z)min
> minCoordinates=min(clump(:,1:3));
> 
> %% Make clump bounding box coordinates start from (0,0,0)
> clump(:,1)=clump(:,1)-minCoordinates(1)+clump(:,4);
> clump(:,2)=clump(:,2)-minCoordinates(2)+clump(:,4);
> clump(:,3)=clump(:,3)-minCoordinates(3)+clump(:,4);
> 
> %% Plot clump
> visualise=true;
> if visualise	
> 	axis equal
> 	camlight
> 	box on; grid on
> 	alpha 0.5
> 	[X,Y,Z]=sphere(50);
> 	for i=1:length(clump(:,4))
> 		hold on
> 		x=clump(i,1);
> 		y=clump(i,2);
> 		z=clump(i,3);
> 		r=clump(i,4);
> 		surf(r*X+x, r*Y+y, r*Z+z, 'FaceColor',rand(1,3), 'EdgeColor','none','FaceAlpha',1)
>     end
>     xlabel('x')
>     ylabel('y')
>     zlabel('z')
> end
> ```
> 
> Hope this helps, Vasileios

**Comment by gxw-ll** [comment]
Okay. Thank you, Professor.
